version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    env_file: .env
    build: ./backend/
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    build: ./nginx/
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media/
      - /backend/foodgram_project/docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - db
      - backend
    ports:
      - 8000:80

